/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://2ccawob74naf7govmmbp4k3xoa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lghnn35zgfdevdxia3wvfaninm",
    "aws_cognito_identity_pool_id": "us-east-1:7aa98d78-b1a5-4f3f-b55f-1aabc80981cb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2ufZOuEdU",
    "aws_user_pools_web_client_id": "46eogqrhd78h9i0k1ave58llvd",
    "oauth": {
        "domain": "state-quiz-staged.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://alexa.amazon.co.jp/spa/skill/account-linking-status.html?vendorId=M2CYCHA45YYAD8/,https://develop.d22h3uk4vvon62.amplifyapp.com/socialAuth/,https://layla.amazon.com/spa/skill/account-linking-status.html?vendorId=MJXE0IWG9YLLG/,https://www.mockcertified.com/socialAuth/",
        "redirectSignOut": "http://localhost:3000/auth/login/,https://alexa.amazon.co.jp/spa/skill/account-linking-status.html?vendorId=M2CYCHA45YYAD8/,https://develop.d22h3uk4vvon62.amplifyapp.com/auth/login/,https://layla.amazon.com/spa/skill/account-linking-status.html?vendorId=MJXE0IWG9YLLG/,https://www.mockcertified.com/auth/login/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "testTable-staged",
            "region": "us-east-1"
        },
        {
            "tableName": "user-staged",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
